### PR TITLE
Introduce working example with docker compose

### PR DESCRIPTION
**Pull request by requaos**
This introduces a Dockerfile for the base repository, so that the build context can encompass the packages other than server, which is why the build context declared in the `docker-compose.yml` is `../.`

For this to be a working example I needed to include the basic service, resource and schema documents. So I followed the rubric set forth in the mongo package, using `/public` for these files.

The app containers `api` and `groupsync` start really fast, so I included a helper function that will continue to attempt connecting to the rabbit instance until it either succeeds or reaches the provided timeout.

### CODE REVIEW

**Comment by requaos** [comment]
Please note that until #39 is satisfied, update operations will yield lookup errors when attempting to lookup the resource before saving the changed version.

**Comment by imulab** [comment]
Hi @requaos 

The refactor work has been done, which includes updated documentation and fixed #37 . Your changes in this PR looks very good, but since it is bound to have some conflict against the refactored version, I will leave this PR open.

Instead of having you redo the work, I will transfer your changes in manually myself and then give you a chance to review them. I will notify you here when it's done. Thank you again for the work! Really appreciate it!

**Comment by imulab** [comment]
Hi @requaos 

Changes are now live on the latest master branch. I made a few changes on top of yours:
- Use one `COPY` directive to copy all stock files as they now live under a single `/public` folder
- Update some environment variable names in `docker-compose.yml` as I changed variable with name `XXX_FOLDER` to `XXX_DIR`
- Added three new targets in make file: `doc` to generate a local godoc preview; `docker` to build docker image; `compose` to start docker-compose stack. Now, the make file can be the single entry point.
- Update README to change `docker-compose up --build` instruction to `make docker compose`

**Comment by requaos** [comment]
@imulab I will go ahead and close this PR. Though I will be opening a tiny PR to address the compose makefile directive. As you currently have `docker-compose up` when we will actually need `docker-compose up --build`. The `--build` flag causes a checksum comparison against the code to see if changes have been made since last start. Without that flag the stack will always start the first set of service containers without including any changes since it was last built.

**Pull request closed without merging**
