### PR TITLE
Added support extension enterprise user

### PR DESCRIPTION
**Pull request by afedyk-sugarcrm**
Added support [Enterprise User Schema Extension](https://tools.ietf.org/html/rfc7643#page-26)

### CODE REVIEW

**Comment by afedyk-sugarcrm** [comment]
@imulab, Can You please look at the pull request:https://github.com/imulab/go-scim/pull/10

**Comment by imulab** [comment]
Thanks @afedyk-sugarcrm !

Your changes look good.

However, I am actually currently working on a new version of this project, which sports 
- a fully dynamic resource model without the use of reflection
- a path/filter parsing mechanism that is intelligent enough to recognize URN prefix without having to hard code it.
- direct JSON and MongoDB BSON serialization and deserialization without having to rely on intermediate data structures

It is in a private repo right now, which I will open source to a `v2` branch here in the coming weeks once it is mature enough. As of now, I think I will postpone merging in your changes as the use case is covered in the second point.

Thanks for your effort and you are welcome to open tickets to discuss potential features you would like in the new version.

**Comment by imulab** [comment]
Closing this PR as the intended feature is implemented in v2.

**Comment by imulab** [comment]
@afedyk-sugarcrm Thanks for the effort.

**Pull request closed without merging**
